### ISSUE TITLE
lock duration

### ISSUE THREAD

**Issue by xiaoch05** [evolutionlandorg/governance-web#4]
https://github.com/evolutionlandorg/governance-web/blob/7f006a9fa22acc1c32ff39e0e0e053c7fb235192/init_web3.js#L615

this should be 
let timeLeft = Number(result[0]) - new Date().getTime() / 1000;
@nblogist

**Comment by nblogist** [comment]
@xiaoch05  This can result in -ve number as the EPOCH for  new Date().getTime() would be a greater number than what the stakinglock would have saved (as it will save EPOCH of time in past and it would be less than present time EPOCH),

**Comment by xiaoch05** [comment]
if the current time is smaller than stakinglock, we should set it to zero and allow unlock. @nblogist
